### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by RobOT05442309** [flathub/ch.protonmail.protonmail-bridge#100]
Hello,

First of all, I would like to thanks all contributors who create and maintain this project as a flatpak. I would like to know if this project is still maintain since their as been 5 new releases over the last 7 month and no updates?

I'm asking this to know if I might be switching to the official proton-bridge or not.

If this is a time issue to maintain this project (I could totally understand that it takes time and contributors are doing this for free), I was wondering if their will be any possibility to let the Proton Bridge made is own update inside the flatpak instead of waiting for validation?

I have no knowledge on how the flatpak process work but as far as I remember and if I get it right when I was using the official bridge under Ubuntu few years ago, the bridge updates was downloaded on the user local space and maybe run from it, only the first "installation" require elevated privileges on the computer.

Since I think it is only a Go binary downloaded on each releases, wouldn't be simple to let the bridge update handle it the same way as it does from the official release allowing write into the sandbox data/cache directory?

This way you (the contributors) wouldn't have to bother checking and validating each versions update.

Thanks for your feedback on this matter. Have a nice day.

**Comment by A6GibKm** [comment]
I havent had time to fix the issues with the lastest version, which there are many btw.

**Comment by RobOT05442309** [comment]
I see, thanks you for your very quick reply, do you think it will be possible to let the bridge auto update itself inside the sandbox to save you time or this is not possible due to library dependencies and other stuff that require you to get a manual checkup and validation every time there is an update?

I'm glad this project is still maintain, I think this is way more useful for everyone in the linux community to get a flatpak instead of depending on binary provide by Proton as deb and rpm only.

**Comment by A6GibKm** [comment]
Please give a try of https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/95 and tell me if it works for you.

**Comment by RobOT05442309** [comment]
After update, it seems to work for me, only downside is that I have to log again into my account but I assume it could be due to the complete rewrite of the app that Proton might have done between version 2 and 3 and the flatpak integration.

Thanks a lot for your work, I didn't want to rush you when opening this issue, I just wanted to know if there was still someone working on this to avoid using flatpak software that have been dropped.

Have a nice day!
