### ISSUE TITLE
Update description to list  "Unofficial Build" or "Not supported by Proton" 

### ISSUE THREAD

**Issue by LBeernaertProton** [flathub/ch.protonmail.protonmail-bridge#105]
I would like to start by  thanking the people involved with bringing Bridge to the Flatpak world.

Unfortunately , we are getting an increasing number of reports for support with issues with the Flatpak version. It would be great if the flathub description could be updated to indicated that this in an unofficial build and not directly supported by Proton. 

Should we wish to provide official releases for Flatpak in the future, we can reverse this course of action.

**Comment by LBeernaertProton** [comment]
@ A6GibKm

**Comment by A6GibKm** [comment]
It might be possible but I am not sure how to make this visible, the readme is not really user facing. 

Whats user facing is Flathub's verification mechanism which flags which apps are supported by upstream, this is not a verified app hence its status as non official is already there.

**Comment by LBeernaertProton** [comment]
Would it not be sufficient to change the description and title in this repo's [config files](https://github.com/flathub/ch.protonmail.protonmail-bridge/blob/master/ch.protonmail.protonmail-bridge.metainfo.xml)?

**Comment by LBeernaertProton** [comment]
Unfortunately the lack of verified marker is not enough to make this point.

**Comment by A6GibKm** [comment]
> Would it not be sufficient to change the description and title in this repo's [config files](https://github.com/flathub/ch.protonmail.protonmail-bridge/blob/master/ch.protonmail.protonmail-bridge.metainfo.xml)?

This is a metainfo of the app itself, not of the distribution of the app. We could do that, but I don't think its the correct place as one might think the app itself is unofficial.

**Comment by LBeernaertProton** [comment]
Thanks. Much appreciated.

Doesn't this metadata not end up in the flathub webpage as well?

**Comment by A6GibKm** [comment]
Yes. I should suffice. By the way, please redirect users with flatpak related issues to this repo .

**Comment by LBeernaertProton** [comment]
:+1:
