### ISSUE TITLE
Update Bridge to version 3.4.2

### ISSUE THREAD

**Issue by RayJW** [flathub/ch.protonmail.protonmail-bridge#112]
The Flatpak is now multiple versions behind. Maybe there is something wrong with the external data checker because it seems like it went unnoticed because the bot didn't create a PR.

**Comment by A6GibKm** [comment]
Hello, thanks for pointing this out. Would you like help to produce a MR? I am not using the app myself. 

I will keep maintaining it, but I would appreciate any help and I cannot guarantee that I will know when a release happens.

**Comment by RayJW** [comment]
I will open a PR for the new version and also try to fix the external data checker in a different one then. :)

**Comment by RayJW** [comment]
Resolved in #113.
