### ISSUE TITLE
Doesn't run at boot.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/ch.protonmail.protonmail-bridge#134]
#### **Reproduction**

Install:

1.	https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40-1.13.iso

1.	```sh
	flatpak update app/ch.protonmail.protonmail-bridge/x86_64/stable --commit=a11f94091eee7084dce03a69ebfb1077edb651131efe6caaf6469c3136786208
	```

#### **Issue**

Despite the relevant preference being enabled:

> ![Screenshot_20240419_164106](https://github.com/flathub/ch.protonmail.protonmail-bridge/assets/42837531/efeacf61-9c5c-4262-8ba0-d1bea997cefa)

It doesn't run at boot:

> ![Screenshot_20240419_164421](https://github.com/flathub/ch.protonmail.protonmail-bridge/assets/42837531/f3004f9f-5ee4-4749-bbfb-86901abda011)

#### **Solution**

If making the preference work isn't possible, I believe that that preference should be disabled, the user directed to use

> ![Screenshot_20240419_164318](https://github.com/flathub/ch.protonmail.protonmail-bridge/assets/42837531/a3ebd441-60f4-4699-9180-fb330b53c3f7)

instead. However, were this the chosen solution, I expect that that would be an issue for upstream?

**Comment by Cloudwalk9** [comment]
Pika Backup, as one example, miraculously adds itself to the autostart as a Flatpak somehow, fwiw. At least I don't recall manually adding it.

**Comment by A6GibKm** [comment]
They probably are using the portal for it. I am closing as it is not actionable from here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/134#issuecomment-2117740950

@A6GibKm , which portal would that be? I don't know of one for autostarting.

**Comment by Cloudwalk9** [comment]
> > https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/134#issuecomment-2117740950
> 
> @A6GibKm , which portal would that be? I don't know of one for autostarting.

My best guess is what ever is for "Allow running in background", but it probably has to be used upstream explicitly.

**Comment by RokeJulianLockhart** [comment]
Yeah, that seems to be the case, per https://github.com/ProtonMail/proton-bridge/issues/277#issuecomment-2061421606.
