### ISSUE TITLE
Installation error: Wrong size for extra data

### ISSUE THREAD

**Issue by MythicalEarth** [flathub/ch.protonmail.protonmail-bridge#17]
New to Flatpak first of all.

Upon installing the protonmail bridge I came across this error:

-------

> **sudo flatpak install flathub ch.protonmail.protonmail-bridge**
> 
> Looking for matches…
> Required runtime for ch.protonmail.protonmail-bridge/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/19.08) found in remote flathub
> Do you want to install it? [Y/n]: y
> 
> ch.protonmail.protonmail-bridge permissions:
>     ipc       network              wayland              x11
>     dri       file access [1]      dbus access [2]
> 
>     [1] ~/.local/state/protonmail/bridge
>     [2] org.freedesktop.Notifications, org.freedesktop.secrets
> 
> 
>         ID                                   Arch   Branch Remote  Download
>  1. [✓] org.freedesktop.Platform             x86_64 19.08  flathub  224.2 MB / 2        ID                                   Arch   Branch Remote  Download
>  1. [✓] org.freedesktop.Platform             x86_64 19.08  flathub 224.2 MB / 238.2 MB
>  2. [✓] org.freedesktop.Platform.GL.default  x86_64 19.08  flathub  92.6 MB / 92.6 MB
>  3. [✓] org.freedesktop.Platform.Locale      x86_64 19.08  flathub  16.7 kB / 318.2 MB
>  4. [✓] org.freedesktop.Platform.VAAPI.Intel x86_64 19.08  flathub   8.7 MB / 8.7 MB
>  5. [✓] org.freedesktop.Platform.openh264    x86_64 19.08  flathub 594.2 kB / 593.4 kB
>  6. [✗] ch.protonmail.protonmail-bridge      x86_64 stable flathub  37.6 MB / 37.6 MB
> 
> Error: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.5-1_amd64.deb
> error: Failed to install ch.protonmail.protonmail-bridge: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.5-1_amd64.deb

-------

OS: Ubuntu 19.10

**Comment by A6GibKm** [comment]
The .deb package was replaced with another with a different hash and size.

**Comment by A6GibKm** [comment]
Thanks for reporting @MythicalEarth.

**Comment by cobratbq** [comment]
I tried installing the test build in #18 , but I get the error now. So, for me at least, it does not seem to be resolved.
```
Error: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.5-1_amd64.deb
error: Failed to install ch.protonmail.protonmail-bridge: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.5-1_amd64.deb
```
Can anyone confirm?

**Comment by sergeyklay** [comment]
The same issue with on Fedora. @A6GibKm Could you please re-release?
