### ISSUE TITLE
Wrong Size for Extra Data: ch.protonmail.protonmail-bridge

### ISSUE THREAD

**Issue by workmat** [flathub/ch.protonmail.protonmail-bridge#24]
Hi,

I'm having an issue installing the bridge client:

ch.protonmail.protonmail-bridge permissions:
    ipc   network   x11   dri   file access [1]   dbus access [2]

    [1] ~/.local/state/protonmail/bridge
    [2] org.freedesktop.secrets

        ID                                        Branch           Op           Remote            Download
 1. [✗] ch.protonmail.protonmail-bridge           stable           i            flathub           38.7 MB / 38.6 MB

Error: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.6-1_amd64.deb
error: Failed to install ch.protonmail.protonmail-bridge: Wrong size for extra data https://protonmail.com/download/beta/protonmail-bridge_1.2.6-1_amd64.deb

**Comment by A6GibKm** [comment]
The size should be computed via `du -b` or `wc -c`.

**Comment by workmat** [comment]
du -b protonmail-bridge_1.2.6-1_amd64.deb 
37884650	protonmail-bridge_1.2.6-1_amd64.deb
