### ISSUE TITLE
Change license to GPLv3

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/ch.protonmail.protonmail-bridge#31]
As referenced in their blog (https://protonmail.com/blog/bridge-open-source/) and in this issue (https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/28), the bridge is now Free Software under the GPLv3 (https://github.com/ProtonMail/proton-bridge/blob/master/LICENSE).

**Comment by A6GibKm** [comment]
In 1.2.7 they removed the eula.txt file that prohibits redistribution. I will change the license and stop using extra-data. Thanks.
