### ISSUE TITLE
Updating libsecret

### ISSUE THREAD

**Issue by f-koehler** [flathub/ch.protonmail.protonmail-bridge#63]
The included version of libsecret `0.19-1` is a couple of versions behind (current is `0.20.4`). Should it be updated to the latest version? I have just tested it and everything seems fine so far.

**Comment by A6GibKm** [comment]
No, any newer version wont be able to login. Eventually this bug will be fixed and then it should be updated using the well-maintained version in https://github.com/flathub/shared-modules

**Comment by A6GibKm** [comment]
Upstream issue https://github.com/flatpak/xdg-desktop-portal/issues/507.

**Comment by f-koehler** [comment]
Oh thanks good to know.

**Comment by A6GibKm** [comment]
This is fixed by https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/85, but please test it and check if it logins and is able to send/retrieve mails. If someone confirms me that it works Ill merge it.
