### ISSUE TITLE
Configuration window is black pane in Wayland

### ISSUE THREAD

**Issue by sanecito** [flathub/ch.protonmail.protonmail-bridge#73]
Symptom:

When the configuration panel is opened it shows as a black box in Wayland. Clicking and holding the top bar will allow you to drag it around, and clicking the top right where the 'X' to close is expected will close it.

![image](https://user-images.githubusercontent.com/3056597/151296782-8bdd56ca-4e18-4c47-93a6-3c392ac01dfa.png)

Impact:

Users can't configure Protonmail Bridge unless they use a X11 based desktop session first.

Replication Steps:

1. Launch a Wayland based desktop session
2. Open Protonmail Bridge (i.e. from the Start Menu or right clicking the icon in the System Tray)

Driver notes: Proprietary Nvidia

**Comment by sHaggYcaT** [comment]
It's actual for me too. I've configured it in the xorg, and switched back to wayland. Than it works. Additional details can be found  [here](https://www.reddit.com/r/ProtonMail/comments/xobf3q/comment/ipyncje/)

**Comment by sHaggYcaT** [comment]
UPDATE:
it works in a case:

```bash
QT_QPA_PLATFORM=wayland  flatpak run --socket=wayland ch.protonmail.protonmail-bridge
```

**Comment by dsommers** [comment]
I wonder if this is fixed now.  I'm running RHEL-8.7 with Wayland.  Proton Mail Bridge v3.1.2 works just as expected in regards to Wayland.

**Comment by sanecito** [comment]
> I wonder if this is fixed now. I'm running RHEL-8.7 with Wayland. Proton Mail Bridge v3.1.2 works just as expected in regards to Wayland.

It is; thanks for flagging this. It has for some months on Fedora 37, but I can't recall which version of KWin this got fixed on.
