### ISSUE TITLE
Proton Mail Bridge not showing up in the tray icon/notification area

### ISSUE THREAD

**Issue by zevlee** [flathub/ch.protonmail.protonmail-bridge#93]
This issue was mentioned in the Proton Bridge repo (https://github.com/ProtonMail/proton-bridge/issues/300) but I figured that I ought to bring up the issue here as this appears to be a Flatpak-specific issue. I installed the RPM version on Fedora 36 and the tray icon shows up fine.

> Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact [bridge@protonmail.ch](mailto:bridge@protonmail.ch).
> 
> The Proton Mail Bridge icon isn't visible in the status bar/notification area. Fedora 36 with GNOME 42.4
> 
> ## Expected Behavior
> It used to show up in the notification area, so the expected behaviour would be that it shows up there.
> 
> ## Current Behavior
> The program runs normally. If you press 'x' to close the window in the top-right corner, it continues to run in the background.
> 
> ## Possible Solution
> It'd be nice to have the program show up in the notification area, instead of having to kill it using `flatpak kill`. Another nice-to-have would be the possibility to exit the program from _within_ the program's main window.
> 
> ## Steps to Reproduce
> 1. Open the GNOME menu (akin to the Windows 'Start' equivalent).
> 2. Open the program 'Proton Mail Bridge'.
> 
> ## Version Information
> 2.3.0
> 
> ## Context (Environment)
> As mentioned further up, it is kinda annoying having to manually kill the program using the CLI.
> 
> ## Detailed Description
> ## Possible Implementation

**Comment by ErikReider** [comment]
Open flatseal and enable access to `D-Bus session bus`

**Comment by A6GibKm** [comment]
> Open flatseal and enable access to `D-Bus session bus`

While this might work as a local "fix" it is a no-go for a flatpak. Note that I was able to see the status icon indicator a few weeks ago when I tested https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/92.

**Comment by ErikReider** [comment]
Excuse my ignorance but wouldn't StatusNotifierItem-* work?

**Comment by A6GibKm** [comment]
> Excuse my ignorance but wouldn't StatusNotifierItem-* work?

I am sorry for the late reply, I just forgot about this... Well I have no clue and no way to test this really, so please if you can test it and open a PR we can have this.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/93#issue-1414417724

@zevlee, using https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso, I am unable to reproduce this:

> ![image](https://github.com/flathub/ch.protonmail.protonmail-bridge/assets/42837531/b415fcb1-755e-44bf-a6f1-b325369d7b6c)

**Comment by zevlee** [comment]
This may be a GNOME-specific problem. Will need to test this at some point.

**Comment by zevlee** [comment]
On GNOME 46, this situation no longer appears to occur, so I will close the issue barring notification of its resurgence.
